export const REPORTS_CONSTANTS = {
  STATUS_LABELS: {
    draft: '下書き',
    submitted: '提出済み',
    approved: '承認済み',
    rejected: '却下',
  },
  PRIORITY_LABELS: {
    low: '低',
    medium: '中',
    high: '高',
  },
  DIFFICULTY_LABELS: {
    easy: '簡単',
    medium: '普通',
    hard: '難しい',
  },
  STEPS: ['基本情報', 'タスク', 'メタデータ'],
  LIST_SCREEN: {
    FILTER_LABELS: {
      ALL: 'すべて',
      DRAFT: '下書き',
      SUBMITTED: '提出済み',
      APPROVED: '承認済み',
      REJECTED: '却下',
    },
    EMPTY_STATE: {
      NO_REPORTS: '日報がありません',
      NO_FILTERED_REPORTS: (status: string) =>
        `${REPORTS_CONSTANTS.STATUS_LABELS[status as keyof typeof REPORTS_CONSTANTS.STATUS_LABELS]}の日報はありません`,
      CREATE_SUGGESTION: '新しい日報を作成してください',
      CREATE_BUTTON: '日報を作成',
    },
    TASK_SUMMARY: 'タスク: ',
    AUTHOR_LABEL: '作成者: ',
  },
  CREATE_SCREEN: {
    NETWORK_STATUS: {
      OFFLINE: 'オフライン',
      ONLINE: 'オンライン',
    },
    FORM_LABELS: {
      DATE: '日付',
      TITLE: 'タイトル',
      CONTENT: '内容',
      REQUIRED_MARKER: ' *',
    },
    PLACEHOLDERS: {
      TITLE: '今日の作業内容を簡潔に',
      CONTENT: '今日の作業内容を詳しく記入してください',
      TASK_NAME: 'タスク名',
      ESTIMATED_HOURS: '予定時間',
      ACTUAL_HOURS: '実績時間',
      CATEGORY: 'カテゴリ',
      METADATA_INPUT: (label: string) => `${label}を入力`,
    },
    BUTTONS: {
      PREVIOUS: '戻る',
      NEXT: '次へ',
      CREATE: '日報を作成',
      CREATING: '作成中...',
      OFFLINE_DISABLED: 'オフライン',
      ADD_TASK: 'タスク追加',
      RETRY: '再試行',
      DISCARD: '破棄',
    },
    TASK_MANAGEMENT: {
      TITLE: 'タスク管理',
      COMPLETED: '完了',
      INCOMPLETE: '未完了',
      EMPTY_STATE: 'タスクを追加して、今日の作業を記録しましょう',
    },
    METADATA_SECTIONS: {
      DIFFICULTY: '難易度',
      ACHIEVEMENTS: '成果・達成事項',
      CHALLENGES: '課題・困った点',
      LEARNINGS: '学んだこと',
      NEXT_ACTIONS: '次のアクション',
    },
    VALIDATION_ERRORS: {
      TITLE_REQUIRED: 'タイトルは必須です',
      TITLE_TOO_LONG: 'タイトルは200文字以内で入力してください',
      CONTENT_REQUIRED: '内容は必須です',
      CONTENT_TOO_LONG: '内容は10000文字以内で入力してください',
    },
    ALERTS: {
      OFFLINE_TITLE: 'オフラインです',
      OFFLINE_MESSAGE: 'インターネット接続を確認してから再度お試しください。',
      CONFLICT_TITLE: 'データ競合が発生しました',
      CONFLICT_MESSAGE: (errorMessage: string) =>
        `${errorMessage}\n\n現在の入力内容を保持して再試行しますか？`,
    },
    TOAST_MESSAGES: {
      CREATING: '日報を作成中...',
      CREATING_SUBTITLE: '少々お待ちください',
      SUCCESS: '日報を作成しました',
      SUCCESS_SUBTITLE: 'リストページに戻ります',
      NETWORK_ERROR: 'ネットワークエラー',
      NETWORK_ERROR_SUBTITLE: 'インターネット接続を確認してください',
      FAILED: '日報の作成に失敗しました',
      RETRY_INFO: '再試行します',
      RETRY_INFO_SUBTITLE: '最新のデータを確認してください',
      DISCARD_INFO: '入力内容を破棄しました',
      DISCARD_INFO_SUBTITLE: 'リストページに戻ります',
    },
  },
  DETAIL_SCREEN: {
    LOADING_TEXT: '読み込み中...',
    SECTIONS: {
      CONTENT: '内容',
      TASKS: 'タスク',
      METADATA: 'メタデータ',
      STATISTICS: '統計',
      APPROVAL_HISTORY: '承認履歴',
      COMMENTS: 'コメント',
    },
    STATISTICS: {
      ESTIMATED_HOURS: '予定時間',
      ACTUAL_HOURS: '実績時間',
      COMMENT_COUNT: 'コメント数',
      COMPLETED_TASKS: (completed: number, total: number) => `${completed}/${total} 完了`,
    },
    REJECTION: {
      TITLE: '却下理由',
    },
    COMMENTS: {
      SYSTEM_AUTHOR: 'システム',
      UNKNOWN_AUTHOR: '不明',
      EMPTY_STATE: 'コメントはありません',
      PLACEHOLDER: 'コメントを入力...',
    },
    ACTIONS: {
      SUBMIT: '提出する',
      APPROVE: '承認',
      REJECT: '却下',
      PROCESSING: '処理中...',
    },
    ALERTS: {
      APPROVE_TITLE: '確認',
      APPROVE_MESSAGE: 'この日報を承認しますか？',
      APPROVE_SUCCESS: '日報を承認しました',
      APPROVE_ERROR: (error: string) => `承認に失敗しました: ${error}`,
      REJECT_TITLE: '確認',
      REJECT_MESSAGE: 'この日報を却下しますか？理由を入力してください。',
      REJECT_REASON_ERROR: '却下理由を入力してください',
      REJECT_SUCCESS: '日報を却下しました',
      REJECT_ERROR: (error: string) => `却下に失敗しました: ${error}`,
      SUBMIT_TITLE: '確認',
      SUBMIT_MESSAGE: 'この日報を提出しますか？',
      SUBMIT_SUCCESS: '日報を提出しました',
      SUBMIT_ERROR: (error: string) => `提出に失敗しました: ${error}`,
      COMMENT_ERROR: 'コメントの送信に失敗しました',
      CANCEL: 'キャンセル',
    },
    APPROVAL_HISTORY: {
      APPROVED_BY: (name: string) => `${name}が承認`,
    },
  },
} as const;
